ares: add sig0 verification.

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -291,7 +291,19 @@ fi
 echo "buildconf: OK"
 
 if test -f "test/buildconf"; then
-  cd test && ./buildconf
+  if cd test; then
+    ./buildconf
+    cd ..
+  fi
 fi
+
+#--------------------------------------------------------------------------
+# Run secp256k1's autogen.sh
+#
+cd secp256k1 || die
+if ! test -f configure; then
+  ./autogen.sh || die "secp256k1 autogen.sh failed."
+fi
+cd .. || die
 
 exit 0
